### ISSUE TITLE
Missing file NeuralSandbox.jar

### ISSUE THREAD

**Issue by DurcoFruk** [Komarovec/NeuralSandbox#1]
NeuralSandbox.jar is missing here, how can I start this project?

**Comment by ghost** [comment]
You can either open it in NetBeans and compile it yourself or you can download release on Github releases page here --> https://github.com/Komarovec/NeuralSandbox/releases

**Comment by DurcoFruk** [comment]
Ohh, thank you. I am an idiot, sorry.
